CREATE SEQUENCE IF NOT EXISTS STOCK_ENTRY_ID_S NOCACHE;

CREATE TABLE IF NOT EXISTS STOCK_PRICE_DETAILS (
    STOCK_ENTRY_ID         BIGINT       DEFAULT STOCK_ENTRY_ID_S.NEXTVAL PRIMARY KEY,
    STOCK                  VARCHAR(20)  NOT NULL,
    OPEN_PRICE             NUMERIC      NOT NULL,
    OPEN_TIME              TIMESTAMP    NOT NULL,
    CLOSE_PRICE            NUMERIC      NOT NULL,
    CLOSE_TIME             TIMESTAMP    NOT NULL,
    LOW_PRICE              NUMERIC      NOT NULL,
    LOW_TIME               TIMESTAMP    NOT NULL,
    HIGH_PRICE             NUMERIC      NOT NULL,
    HIGH_TIME              TIMESTAMP    NOT NULL,
    TOTAL_TRADES_COUNT     BIGINT       NOT NULL,
    TOTAL_TRADED_SHARES    BIGINT       NOT NULL,
    TOTAL_TRADED_VALUE     NUMERIC
);